Add http redirects (includes http -> https redirects)
SKCraft/Launcher pull request #272
Opened 2018-12-24 12:32 UTC by jkroepke

Related: #154
Fixes: #93

I add the rediection code inside the HttpRequest Class so any http request from the launcher are able to handle redirects.

2020-12-24 22:58 UTC, hedgehog1029 commented
Definitely interested in merging this but there are a couple of fixes needed:
1. Code style - there's some weird spacing and such
2. The user agent was changed here unneccesarily - can this be reverted
3. Should probably handle 307, 308 and maybe 303 status codes

2020-12-24 23:04 UTC, hedgehog1029 requested changes
Obviously apply all these changes to the bootstrap copy too.

2020-12-24 23:04 UTC, hedgehog1029 commented on launcher/src/main/java/com/skcraft/launcher/util/HttpRequest.java
> +                conn        = (HttpURLConnection) reformat(connectUrl).openConnection();
Weird whitespace here

2020-12-24 23:04 UTC, hedgehog1029 commented on launcher/src/main/java/com/skcraft/launcher/util/HttpRequest.java
> +                conn.setRequestProperty("User-Agent", "SKCraft Launcher");
Can this be reverted to the previous user-agent, `"Mozilla/5.0 (Java) SKMCLauncher"`

2020-12-24 23:04 UTC, hedgehog1029 commented on launcher/src/main/java/com/skcraft/launcher/util/HttpRequest.java
> +                    case HttpURLConnection.HTTP_MOVED_TEMP:
Handle some other 3xx codes here

2020-12-25 21:42 UTC, jkroepke commented
this is almost 2 year old. I guess using a high level http client (or java 11?) http client should a better option.

2020-12-25 21:42 UTC, closed without merging